package util;

public class Variables {
  public static long START_TIME;
  public static boolean EXHAUSTIVE;
  public static int TIME_LIMIT, UPDATE_ITERATIONS,
      ROOM_PROP_PEN, PREF_CAP_PEN,
      SPECIALITY_PEN, GENDER_PEN,
      TRANSFER_PEN, DELAY_PEN, CAP_VIOL_PEN,
      PCR, PSR, PSHA, PSWA, SWAP_LOOPS,
      WE_MIN, PC_MAX, DELTA, MAX_HBS_ITERATIONS,
      INITIAL_TOTAL_ITERATIONS, INIT_ITERATIONS,
      SUBPROBLEM_TOTAL_ITERATIONS, SUB_ITERATIONS,
      REPAIR_TOTAL_ITERATIONS, REP_ITERATIONS,
      RND_ITERATIONS;
  public static double EXTEND, INSTANCE_SCALE,
      T_START, T_STOP, ALPHA,
      TRADEOFF,
      PENALTY_COEFFICIENT, CONSTANT_PENALTY_ZONE, PENALTY_UPDATE_OFFSET,
      PENALTY_INCREASE, PENALTY_DECREASE, REPAIR_INCREASE;
  public static String PATH, INSTANCE;
}
